name: Publish documentations
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn docs
      - run: echo '<meta http-equiv="refresh" content="0;url=index.html" />"' > docs/404.html
      - run: npx sass src/docs.scss >> docs/assets/css/main.css
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
